name: Nix Flake Check

on:
  push:
    branches: [ "main", "feat/*", "fix/*", "refactor/*", "docs/*", "chore/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Magic Nix Cache
        uses: cachix/cachix-action@v15
        with:
          name: unity-via-distrobox
          skipPush: true

      - name: Check Nix Flake
        run: nix flake check --show-trace --accept-flake-config
