name: Nix Flake Check

on:
  push:
    branches: [ "main", "feat/*", "fix/*", "refactor/*", "docs/*", "chore/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix Formatting
        run: |
          FMT=$(nix build .#formatter.x86_64-linux --print-out-paths)
          "$FMT/bin/nixfmt" --check $(git ls-files '*.nix')

      - name: Check Nix Flake
        run: nix flake check --show-trace --accept-flake-config
